name: Build

on:
  workflow_call:
    inputs:
      REGISTRY:
        required: true
        type: string
    secrets:
      GITLAB_LOGIN:
        required: true
      GITLAB_PASS:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: wmgcat-net/frontend
        
      - name: Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ secrets.GITLAB_LOGIN }}
          password: ${{ secrets.GITLAB_PASS }}
            
      - name: Build and push
        run: |
          npm i
          npm run docker:public